class LocalizationService {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'WeatherUK Radar',
      'support': 'Support',
      'rate_app': 'Rate the App',
      'share_app': 'Share with Friends',
      'share_text': 'Check out WeatherUK Radar! The ultimate live weather radar & forecast app.',
      'nav_back': 'Back',
      'nav_home': 'Home',
      'nav_favorites': 'Favorites',
      'nav_cities': 'Cities',
      'nav_radar': 'Radar',
      'nav_settings': 'Settings',
      'label_dark_mode': 'Dark Mode',
      'label_language': 'Language',
      'forecast_hourly': 'Hourly Forecast',
      'forecast_7day': '7-Day Forecast',
      'settings': 'Settings',
      'units': 'Units',
      'notifications': 'Notifications',
      'customization': 'Customization',
      'unit_celsius': 'Unit: Celsius (°C)',
      'unit_fahrenheit': 'Unit: Fahrenheit (°F)',
      'pressure_unit_mb': 'Pressure Unit: mb',
      'pressure_unit_hpa': 'Pressure Unit: hPa',
      'general_alerts': 'General Weather Alerts',
      'rain_alerts': 'Rain Alerts',
      'temp_alerts': 'Temperature Drop Alerts',
      'hazard_alerts': 'Special Hazards & AQI',
      'app_language': 'App Language',
      'visibility': 'Visibility',
      'humidity': 'Humidity',
      'uv_index': 'UV Index',
      'wind_speed': 'Wind Speed',
      'pressure': 'Pressure',
      'sun_title': 'Sunrise & Sunset',
      'air_quality': 'Air Quality',
      'excellent': 'Excellent',
      'good': 'Good',
      'moderate': 'Moderate',
      'poor': 'Poor',
      'very_poor': 'Very Poor',
      'low': 'Low',
      'high': 'High',
      'very_high': 'Very High',
      'clear_visibility': 'Clear visibility',
      'slight_haze': 'Slight haze in the air',
      'reduced_visibility': 'Reduced visibility, use caution',
      'low_visibility': 'Low visibility due to fog',
      'extreme_fog': 'Extreme fog',
      'km_unit': 'km',
      'clear_sky': 'Clear Sky',
      'sunny': 'Sunny',
      'mainly_clear': 'Mainly Clear',
      'mostly_sunny': 'Mostly Sunny',
      'partly_cloudy': 'Partly Cloudy',
      'overcast': 'Overcast',
      'foggy': 'Foggy',
      'light_drizzle': 'Light Drizzle',
      'moderate_drizzle': 'Moderate Drizzle',
      'dense_drizzle': 'Dense Drizzle',
      'light_freezing_drizzle': 'Light Freezing Drizzle',
      'dense_freezing_drizzle': 'Dense Freezing Drizzle',
      'light_rain': 'Light Rain',
      'moderate_rain': 'Moderate Rain',
      'heavy_rain': 'Heavy Rain',
      'light_freezing_rain': 'Light Freezing Rain',
      'heavy_freezing_rain': 'Heavy Freezing Rain',
      'light_snow': 'Light Snow',
      'moderate_snow': 'Moderate Snow',
      'heavy_snow': 'Heavy Snow',
      'snow_grains': 'Snow Grains',
      'light_rain_showers': 'Light Rain Showers',
      'moderate_rain_showers': 'Moderate Rain Showers',
      'violent_rain_showers': 'Violent Rain Showers',
      'light_snow_showers': 'Light Snow Showers',
      'heavy_snow_showers': 'Heavy Snow Showers',
      'thunderstorm': 'Thunderstorm',
      'thunderstorm_hail_light': 'Thunderstorm with Light Hail',
      'thunderstorm_hail_heavy': 'Thunderstorm with Heavy Hail',
      'unknown': 'Unknown',
      'retry': 'Retry',
      'today': 'Today',
      'wind': 'Wind',
      'rain': 'Rain',
      'feels_like': 'Feels',
      'sport_running': 'Running',
      'sport_cycling': 'Cycling',
      'sport_hiking': 'Hiking',
      'status_avoid': 'Avoid',
      'status_decent': 'Decent',
      'status_excellent': 'Excellent',
      'status_good': 'Good',
      'advice_storm': 'Storm: stay indoors ⛈️',
      'advice_not_ideal': 'Not ideal conditions 🚫',
      'advice_decent_template': 'Decent conditions 🌤️',
      'advice_excellent_template': 'Excellent conditions ✨',
      'advice_good_template': 'Good conditions now',
      'smart_hydration': 'Stay hydrated 💧',
      'smart_dress_warm': 'Dress warm ❄️',
      'smart_strong_wind': 'Strong wind 💨',
      'smart_high_humidity': 'High humidity 🌫️',
      'smart_great_day': 'Great day ✨',
      'smart_stay_indoors': 'Stay indoors 🏠',
      'more_details': 'More Details & Graphs',
      'daily_insights': 'Daily Insights',
      'popular_cities': 'Popular UK Cities',
      'search_cities': 'Search Results',
      'fav_no_items': 'No cities found',
      'search_city': 'Search UK city...',
      'aqi_title': 'Air Quality Index',
      'aqi_advice_good': 'The air is clean and healthy.',
      'sport_outdoor': 'Sport & Outdoor',
      'recent_searches': 'Recent Searches',
      'smart_okay_outings': 'Okay for outings ☔',
      'smart_enjoy_day': 'Enjoy your day! 😊',
      'aqi_levels_title': 'Air Quality Levels',
      'aqi_good': 'Good',
      'aqi_moderate': 'Moderate',
      'aqi_unhealthy_sensitive': 'Unhealthy (Sensitive)',
      'aqi_unhealthy': 'Unhealthy',
      'aqi_very_unhealthy': 'Very Unhealthy',
      'aqi_hazardous': 'Hazardous',
      'got_it': 'Got it',
      'cities_title': 'Cities',
      'use_location': 'Use My Current Location',
      'famous_cities': 'Famous UK Cities',
      'select_city_arrow': 'Select →',
      'favorites_title': 'Favorites',
      'fav_add_hint': 'Add cities by clicking the heart icon',
      'fav_saved_location': 'Saved Location',
      'remove_fav': 'Remove',
      'outdoor_perfect': 'Perfect for outdoor activities',
      'outdoor_moderate': 'Moderate conditions',
      'outdoor_poor': 'Not recommended',
      'best_time_at': 'Best time: %s',
      'condition_stable': 'Condition stable',
      'steady': 'Steady',
      'pollutants_title': 'Main Pollutants',
      'health_advice_title': 'Health Advice',
      'aqi_forecast_title': '24-Hour AQI Forecast',
      'aqi_fair': 'Fair',
      'aqi_extremely_poor': 'Extremely Poor',
      'pm2_5_desc': 'Fine particles that can penetrate deep into the lungs and enter the bloodstream.',
      'pm10_desc': 'Inhalable particles that can cause respiratory issues and aggravate asthma.',
      'co_desc': 'A colorless, odorless gas that can be harmful when inhaled in large amounts.',
      'no2_desc': 'A gas primarily from vehicle emissions that can irritate the airways.',
      'o3_desc': 'Ground-level ozone can trigger chest pain, coughing, and throat irritation.',
      'so2_desc': 'A gas from burning fossil fuels that can affect the respiratory system.',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'solar_cycle': 'Solar Cycle',
      'sunrise': 'Sunrise',
      'sunset': 'Sunset',
      'analytics_insights': 'Analytics & Insights',
      'additional_data': 'Additional Data',
      'max_wind': 'Max Wind',
      'precip_sum': 'Precipitation Sum',
      'trend_24h': '24-Hour Trend',
      'status_now': 'NOW',
      'status_forecast': 'FORECAST',
    },
  };

  static String translate(String key, [String langCode = 'en']) {
    final map = _translations[langCode] ?? _translations['en']!;
    return map[key] ?? _translations['en']![key] ?? key;
  }
}
